// ═══════════════════════════════════════════════════════════════════
// UPSC Digital Atlas — Data Module v3
// ═══════════════════════════════════════════════════════════════════

export const CAT = {
  city:{color:'#2563EB',icon:'🏙️',label:'City'},
  river:{color:'#0891B2',icon:'🌊',label:'River'},
  mountain:{color:'#7C3AED',icon:'⛰️',label:'Mountain'},
  pass:{color:'#DC2626',icon:'🏔️',label:'Pass'},
  strait:{color:'#0D9488',icon:'🌀',label:'Strait'},
  lake:{color:'#0284C7',icon:'💧',label:'Lake'},
  island:{color:'#059669',icon:'🏝️',label:'Island'},
  desert:{color:'#D97706',icon:'🏜️',label:'Desert'},
  plateau:{color:'#92400E',icon:'🗻',label:'Plateau'},
  canal:{color:'#0E7490',icon:'⚓',label:'Canal'},
  boundary:{color:'#BE185D',icon:'🔲',label:'Boundary'},
  pyq:{color:'#E11D48',icon:'📝',label:'PYQ'},
  custom:{color:'#6D28D9',icon:'📌',label:'Custom'},
};

export const indiaData=[
{id:'ic1',name:'New Delhi',lat:28.6139,lng:77.209,type:'city',info:'National capital. Seat of Parliament, Supreme Court, Rashtrapati Bhavan. On Yamuna. Lutyens\' design. UNESCO: Qutub Minar, Humayun\'s Tomb, Red Fort.',upscRelevance:'Constitutional bodies HQ. UNESCO sites. NCT — unique governance. Rajpath → Kartavya Path.'},
{id:'ic2',name:'Mumbai',lat:19.076,lng:72.8777,type:'city',info:'Financial capital. RBI HQ, BSE, NSE, SEBI. Konkan coast. Natural harbour. Elephanta Caves UNESCO.',upscRelevance:'RBI, SEBI — Economy. Western Ghats proximity. Bombay High — offshore oil.'},
{id:'ic3',name:'Kolkata',lat:22.5726,lng:88.3639,type:'city',info:'Former British capital (till 1911). On Hooghly. Only riverine major port. Victoria Memorial.',upscRelevance:'Bengal Renaissance, Partition. Ganga-Brahmaputra delta. Sundarbans gateway.'},
{id:'ic4',name:'Chennai',lat:13.0827,lng:80.2707,type:'city',info:'Tamil Nadu capital. Coromandel Coast. "Detroit of India". Mahabalipuram UNESCO nearby.',upscRelevance:'Cyclone-prone coast. Dravidian architecture. Bharatanatyam.'},
{id:'ic5',name:'Bengaluru',lat:12.9716,lng:77.5946,type:'city',info:'IT capital. HQ: ISRO, HAL, NAL. Deccan Plateau (~920m).',upscRelevance:'ISRO HQ — space missions. HAL — defence. Deccan Plateau.'},
{id:'ic6',name:'Leh',lat:34.1526,lng:77.5771,type:'city',info:'Ladakh UT capital. ~3,500m. Indus Valley. Cold desert. Near LAC.',upscRelevance:'Cold desert. India-China LAC. Galwan Valley. Pangong Tso.'},
{id:'ic7',name:'Varanasi',lat:25.3176,lng:83.006,type:'city',info:'Oldest city. Holy city on Ganga. Sarnath — Buddha\'s first sermon.',upscRelevance:'Ganga ghats. Buddhist history. Silk weaving GI.'},
{id:'ic8',name:'Port Blair',lat:11.6234,lng:92.7265,type:'city',info:'A&N Islands capital. Cellular Jail. Only tri-service command.',upscRelevance:'Strategic near Malacca. Tri-service command. Freedom struggle.'},
{id:'ic9',name:'Hyderabad',lat:17.385,lng:78.4867,type:'city',info:'Telangana capital. DRDO labs. Charminar. "Vaccine Capital".',upscRelevance:'Pharma hub. Charminar — Qutb Shahi. Nizam history.'},
{id:'ic10',name:'Ahmedabad',lat:23.0225,lng:72.5714,type:'city',info:'Gujarat. Sabarmati River. UNESCO World Heritage City (2017). Textile industry.',upscRelevance:'First Indian UNESCO Heritage City. Sabarmati Ashram.'},
{id:'ic11',name:'Guwahati',lat:26.1445,lng:91.7362,type:'city',info:'Gateway to NE India. On Brahmaputra. Kamakhya Temple.',upscRelevance:'NE connectivity. Brahmaputra floods. Act East Policy.'},
{id:'ic12',name:'Srinagar',lat:34.0837,lng:74.7973,type:'city',info:'J&K summer capital. Dal Lake. On Jhelum. ~1,585m.',upscRelevance:'Article 370 (revoked). Kashmir. Dal Lake ecology.'},
{id:'ic13',name:'Thiruvananthapuram',lat:8.5241,lng:76.9366,type:'city',info:'Kerala capital. VSSC (rocket launches). Padmanabhaswamy Temple.',upscRelevance:'VSSC — Thumba. Monsoon arrival point (June 1).'},
{id:'ic14',name:'Imphal',lat:24.817,lng:93.9368,type:'city',info:'Manipur capital. Battle of Imphal 1944. Loktak Lake.',upscRelevance:'INA history. Loktak Lake. AFSPA debates.'},
{id:'ic15',name:'Gangtok',lat:27.3389,lng:88.6065,type:'city',info:'Sikkim capital. ~1,650m. 100% organic state.',upscRelevance:'First organic state. Kangchenjunga NP UNESCO.'},
{id:'ic16',name:'Shimla',lat:31.1048,lng:77.1734,type:'city',info:'HP capital. Former British summer capital. ~2,200m.',upscRelevance:'Shimla Agreement 1972. Lesser Himalayas.'},
{id:'ic17',name:'Bhopal',lat:23.2599,lng:77.4126,type:'city',info:'MP capital. "City of Lakes". 1984 gas tragedy. Bhimbetka UNESCO nearby.',upscRelevance:'Bhopal Tragedy — env law. Bhimbetka — prehistoric art.'},
{id:'ic18',name:'Jaipur',lat:26.9124,lng:75.7873,type:'city',info:'Rajasthan capital. "Pink City". Amber Fort, Jantar Mantar UNESCO.',upscRelevance:'UNESCO Walled City 2019. Jantar Mantar — astronomy.'},
{id:'ic19',name:'Itanagar',lat:27.0844,lng:93.6053,type:'city',info:'Arunachal Pradesh capital. Near McMahon Line. Tawang nearby.',upscRelevance:'McMahon Line dispute. Tawang monastery. 1962 war.'},
{id:'ic20',name:'Shillong',lat:25.5788,lng:91.8933,type:'city',info:'Meghalaya capital. "Scotland of East". Cherrapunji nearby — highest rainfall.',upscRelevance:'Cherrapunji/Mawsynram — rainfall. Living root bridges.'},
{id:'ir1',name:'Ganga',lat:25.4358,lng:81.8463,type:'river',info:'2,525 km. Gangotri → Devprayag (Bhagirathi+Alaknanda). Tributaries: Yamuna, Son, Ghaghara, Gandak, Kosi. Sundarbans delta.',upscRelevance:'Namami Gange. Sundarbans UNESCO/Ramsar. Farakka (India-Bangladesh). National River.'},
{id:'ir2',name:'Brahmaputra',lat:26.19,lng:91.746,type:'river',info:'2,900 km. Angsi Glacier (Tibet) → Tsangpo → Dihang. Braided. Majuli — largest river island.',upscRelevance:'Antecedent river. India-China water. Majuli erosion. Floods.'},
{id:'ir3',name:'Narmada',lat:22.6783,lng:75.8573,type:'river',info:'1,312 km. Amarkantak (MP). West-flowing through rift valley. Sardar Sarovar Dam.',upscRelevance:'Rift valley. West-flowing (trap!). Narmada Bachao Andolan. Vindhya-Satpura divide.'},
{id:'ir4',name:'Godavari',lat:16.96,lng:81.78,type:'river',info:'1,465 km. "Dakshin Ganga". Trimbakeshwar, Nashik. Longest peninsular river.',upscRelevance:'Longest peninsular. Polavaram Project. Water disputes (MH/TS/AP).'},
{id:'ir5',name:'Kaveri',lat:12.4244,lng:76.6549,type:'river',info:'800 km. Talakaveri, Kodagu. Shivanasamudra Falls. Grand Anicut.',upscRelevance:'Cauvery Dispute (KA vs TN). Grand Anicut — Cholas. PYQ: 2018.'},
{id:'ir6',name:'Indus',lat:34.1674,lng:77.5786,type:'river',info:'3,180 km. Near Mansarovar. Through Ladakh → Pakistan. IWT 1960.',upscRelevance:'Indus Water Treaty. IVC. Trans-Himalayan river.'},
{id:'ir7',name:'Krishna',lat:16.5175,lng:80.6306,type:'river',info:'1,400 km. Mahabaleshwar (MH). Nagarjuna Sagar Dam.',upscRelevance:'Krishna Water Tribunal. 2nd longest peninsular.'},
{id:'ir8',name:'Yamuna',lat:28.6841,lng:77.2175,type:'river',info:'1,376 km. Yamunotri Glacier. Largest tributary of Ganga. Sangam at Prayagraj.',upscRelevance:'Most polluted stretch. Yamuna Action Plan. Kumbh Mela.'},
{id:'ir9',name:'Mahanadi',lat:20.4625,lng:85.8828,type:'river',info:'858 km. Sihawa (CG). Hirakud Dam — longest in India. East-flowing.',upscRelevance:'Hirakud Dam. East-flowing (not west — trap!). CG-Odisha dispute.'},
{id:'ir10',name:'Tapti',lat:21.1702,lng:72.8311,type:'river',info:'724 km. Betul (MP). West-flowing through rift valley. Parallel to Narmada.',upscRelevance:'West-flowing. Rift valley. South of Satpura range.'},
{id:'ir11',name:'Sutlej',lat:31.1,lng:77.17,type:'river',info:'1,450 km. Rakas Lake (Tibet). Antecedent. Bhakra Nangal Dam.',upscRelevance:'IWT — allocated to India. Bhakra Dam. Antecedent river.'},
{id:'ir12',name:'Periyar',lat:10.0,lng:76.5,type:'river',info:'244 km. Longest in Kerala. West-flowing. Mullaperiyar Dam dispute.',upscRelevance:'West-flowing Kerala. Mullaperiyar dispute (KL vs TN). Periyar Tiger Reserve.'},
{id:'im1',name:'Kangchenjunga',lat:27.7025,lng:88.1475,type:'mountain',info:'8,586m. 3rd highest globally. Highest in India. Sikkim-Nepal border.',upscRelevance:'Highest peak in India. UNESCO NP. India-Nepal boundary.'},
{id:'im2',name:'Western Ghats',lat:14.5,lng:75.5,type:'mountain',info:'~1,600 km. UNESCO 2012. Older than Himalayas. 5,000+ flowering plants. SW monsoon barrier.',upscRelevance:'Biodiversity hotspot. Rain shadow. Gaps (Palakkad, Bhor, Thal). PYQ: 2022, 2019.'},
{id:'im3',name:'Anamudi',lat:10.1667,lng:77.05,type:'mountain',info:'2,695m. Highest in Western Ghats & South India. Eravikulam NP.',upscRelevance:'Highest in South India. Nilgiri Tahr. Shola-grassland.'},
{id:'im4',name:'Siachen Glacier',lat:35.4167,lng:77.1,type:'mountain',info:'76 km. Karakoram. World\'s highest battleground. Op Meghdoot 1984.',upscRelevance:'Op Meghdoot. India-Pakistan. Karakoram glacier.'},
{id:'im5',name:'Eastern Ghats',lat:14.5,lng:79.5,type:'mountain',info:'Discontinuous. Cut by Godavari, Krishna, Kaveri, Mahanadi.',upscRelevance:'Discontinuous (vs WG continuous — trap). Bauxite deposits.'},
{id:'im6',name:'Nanda Devi',lat:30.3733,lng:79.9742,type:'mountain',info:'7,816m. 2nd highest in India. Uttarakhand. UNESCO NP + BR.',upscRelevance:'2nd highest. Valley of Flowers nearby. UNESCO.'},
{id:'im7',name:'Aravalli',lat:25.0,lng:73.5,type:'mountain',info:'~692 km. Oldest fold mountains in India. Guru Shikhar (1,722m). Rajasthan.',upscRelevance:'Oldest mountains. Blocks moisture → Thar desert. Minerals.'},
{id:'im8',name:'Vindhya Range',lat:24.0,lng:79.0,type:'mountain',info:'Divides N & S India. ~1,050 km. Parallel to Narmada (north bank). Bhimbetka caves.',upscRelevance:'N-S India divide. Narmada flows in Vindhya-Satpura rift.'},
{id:'ip1',name:'Nathu La',lat:27.0767,lng:88.83,type:'pass',info:'4,310m. India-China, Sikkim. Reopened 2006. 1967 clash.',upscRelevance:'India-China trade. 1967 clash. PYQ: 2017.'},
{id:'ip2',name:'Palakkad Gap',lat:10.75,lng:76.6833,type:'pass',info:'Major WG break. ~40 km wide. NE monsoon into Kerala.',upscRelevance:'Most asked WG gap. Monsoon mechanism. PYQ: 2019, 2014.'},
{id:'ip3',name:'Karakoram Pass',lat:35.52,lng:77.83,type:'pass',info:'5,540m. India-China, Ladakh. On LAC.',upscRelevance:'Highest pass on India border. LAC. Aksai Chin.'},
{id:'ip4',name:'Rohtang Pass',lat:32.3722,lng:77.2478,type:'pass',info:'3,978m. HP. Atal Tunnel (longest above 10,000ft).',upscRelevance:'Atal Tunnel — Ladakh connectivity. Pir Panjal crossing.'},
{id:'ip5',name:'Zoji La',lat:34.2833,lng:75.5167,type:'pass',info:'3,528m. J&K. Srinagar-Leh gateway. Z-Morh tunnel.',upscRelevance:'Srinagar-Leh route. Great Himalayas crossing.'},
{id:'ip6',name:'Shipki La',lat:31.7833,lng:78.7667,type:'pass',info:'4,500m. HP-Tibet. Sutlej enters India here.',upscRelevance:'Sutlej entry. India-China border. Trade route.'},
{id:'ip7',name:'Bom Di La',lat:27.27,lng:92.4,type:'pass',info:'2,217m. Arunachal Pradesh. Tawang approach. 1962 war route.',upscRelevance:'1962 Indo-China war. Tawang accessibility.'},
{id:'ip8',name:'Jelep La',lat:27.3,lng:88.87,type:'pass',info:'4,267m. Sikkim-Tibet. Old Lhasa trade route.',upscRelevance:'Historic Sikkim-Tibet trade. Near Nathu La.'},
{id:'il1',name:'Chilika Lake',lat:19.72,lng:85.32,type:'lake',info:'Largest coastal lagoon (1,100 km²). Brackish. Odisha. 1st Ramsar 1981. Irrawaddy dolphins.',upscRelevance:'Largest brackish lagoon. 1st Indian Ramsar. PYQ: 2018.'},
{id:'il2',name:'Pangong Tso',lat:33.7578,lng:78.6635,type:'lake',info:'Endorheic salt lake. ~4,350m. 134 km. 60% in China. 2020 standoff.',upscRelevance:'India-China standoff. Endorheic lake. LAC. PYQ: 2020.'},
{id:'il3',name:'Loktak Lake',lat:24.55,lng:93.8,type:'lake',info:'Largest freshwater in NE. Manipur. Phumdis. Keibul Lamjao NP — only floating NP.',upscRelevance:'Only floating NP. Sangai deer. PYQ: 2016.'},
{id:'il4',name:'Wular Lake',lat:34.37,lng:74.64,type:'lake',info:'Largest freshwater lake in India. J&K. Jhelum. Ramsar.',upscRelevance:'Largest freshwater (not Chilika — brackish). Jhelum basin.'},
{id:'il5',name:'Sambhar Lake',lat:26.9167,lng:75.1,type:'lake',info:'Largest inland saline lake. Rajasthan. Salt production. Ramsar.',upscRelevance:'Largest inland salt lake. Flamingos. Ramsar.'},
{id:'il6',name:'Vembanad Lake',lat:9.57,lng:76.35,type:'lake',info:'Longest lake in India (96 km). Kerala backwaters. Kuttanad below sea level.',upscRelevance:'Longest lake. Kuttanad — below sea-level farming.'},
{id:'il7',name:'Dal Lake',lat:34.09,lng:74.84,type:'lake',info:'Srinagar. Houseboats. Floating gardens. Eutrophication threat.',upscRelevance:'Kashmir tourism. Eutrophication case study.'},
{id:'ii1',name:'Barren Island',lat:12.278,lng:93.858,type:'island',info:'Only active volcano in South Asia. Andaman Sea.',upscRelevance:'Only active volcano in India. Plate tectonics.'},
{id:'ii2',name:'Majuli',lat:26.95,lng:94.1667,type:'island',info:'World\'s largest river island. Brahmaputra. Sattras. Erosion threat.',upscRelevance:'Largest river island. Erosion. PYQ: 2016.'},
{id:'ii3',name:'Lakshadweep',lat:10.5667,lng:72.6417,type:'island',info:'36 coral islands. Only coral atolls in India. Arabian Sea.',upscRelevance:'Coral atolls. EEZ. Marine biodiversity.'},
{id:'ipl1',name:'Deccan Plateau',lat:17.0,lng:78.0,type:'plateau',info:'Triangular. WG (W), EG (E), Satpura-Vindhya (N). Black soil. Avg 600m.',upscRelevance:'Black soil — cotton. Basaltic lava. Peninsular rivers.'},
{id:'ipl2',name:'Ladakh Plateau',lat:34.0,lng:78.0,type:'plateau',info:'Tibetan Plateau extension. ~4,500m. Cold desert. Changthang.',upscRelevance:'Cold desert. Pashmina goats. Changpa nomads.'},
{id:'ipl3',name:'Chota Nagpur',lat:23.4,lng:85.3,type:'plateau',info:'Jharkhand. Iron, coal, mica, manganese. "Ruhr of India".',upscRelevance:'Mineral-rich. Damodar Valley. Tribal belt. PYQ: 2017.'},
{id:'ipl4',name:'Malwa Plateau',lat:23.5,lng:76.0,type:'plateau',info:'MP-Rajasthan. Black soil. Chambal ravines. Opium production.',upscRelevance:'Black soil. Chambal ravines — badlands. Tributaries of Yamuna.'},
{id:'pyq1',name:'Silent Valley NP',lat:11.0833,lng:76.4167,type:'pyq',info:'Kerala. WG. Tropical evergreen. Lion-tailed macaque. Saved from dam.',upscRelevance:'Environmental activism. LTM. PYQ: 2019, 2016.'},
{id:'pyq2',name:'Katchatheevu',lat:9.3833,lng:79.5333,type:'pyq',info:'Island in Palk Strait. Ceded to Sri Lanka 1974. Fishing dispute.',upscRelevance:'India-SL maritime boundary. PYQ: 2024.'},
{id:'pyq3',name:'Dzukou Valley',lat:25.5167,lng:93.9833,type:'pyq',info:'Nagaland-Manipur border. ~2,400m. Dzukou lily. Indo-Burma hotspot.',upscRelevance:'NE biodiversity. PYQ: 2024.'},
{id:'pyq4',name:'Polavaram',lat:17.249,lng:81.6436,type:'pyq',info:'Dam on Godavari, AP. National project. Inter-state submergence.',upscRelevance:'Godavari projects. Water disputes. PYQ: 2019.'},
{id:'pyq5',name:'Indira Point',lat:6.7467,lng:93.8425,type:'pyq',info:'Southernmost point. Nicobar. Submerged after 2004 tsunami.',upscRelevance:'Extreme points. PYQ: 2017, 2012.'},
{id:'pyq6',name:'Sundarbans',lat:21.9497,lng:89.1833,type:'pyq',info:'Largest mangrove. Ganga-Brahmaputra delta. UNESCO. Tiger reserve.',upscRelevance:'Mangrove. Tiger. Climate — sea level. PYQ: 2023, 2019.'},
{id:'pyq7',name:'Doklam',lat:27.3569,lng:89.0558,type:'pyq',info:'India-Bhutan-China tri-junction. 2017 standoff.',upscRelevance:'India-China-Bhutan. 2017 standoff. PYQ: 2018.'},
{id:'pyq8',name:'Sir Creek',lat:23.7,lng:68.8,type:'pyq',info:'Gujarat-Sindh marshland. Disputed India-Pakistan maritime.',upscRelevance:'India-Pak maritime dispute. Rann of Kutch. PYQ: 2016.'},
{id:'pyq9',name:'Nubra Valley',lat:34.7,lng:77.6,type:'pyq',info:'Ladakh. Shyok-Nubra confluence. Bactrian camels.',upscRelevance:'Siachen approach. Double-humped camels. PYQ: 2018.'},
{id:'pyq10',name:'Dandakaranya',lat:19.5,lng:81.0,type:'pyq',info:'Forest: CG, MH, Odisha, AP. Tribal areas. Bastar.',upscRelevance:'Tribal areas. LWE. PVTGs. PYQ: 2019.'},
];

export const worldData=[
{id:'wc1',name:'Geneva',lat:46.2044,lng:6.1432,type:'city',info:'Switzerland. WTO, WHO, UNHCR, WIPO, ICRC, CERN, ILO.',upscRelevance:'International orgs HQ. Geneva Conventions.'},
{id:'wc2',name:'The Hague',lat:52.0705,lng:4.3007,type:'city',info:'Netherlands. ICJ, ICC. Peace Palace.',upscRelevance:'ICJ (Kulbhushan Jadhav). ICC vs ICJ. Intl law.'},
{id:'wc3',name:'Vienna',lat:48.2082,lng:16.3738,type:'city',info:'Austria. IAEA, OPEC, OSCE, UNODC, UNIDO.',upscRelevance:'IAEA — nuclear. OPEC HQ. JCPOA.'},
{id:'wc4',name:'Nairobi',lat:-1.2921,lng:36.8219,type:'city',info:'Kenya. UNEP, UN-Habitat HQ.',upscRelevance:'UNEP HQ. Only UN env body in developing world.'},
{id:'wc5',name:'Beijing',lat:39.9042,lng:116.4074,type:'city',info:'China. SCO, AIIB, NDB HQ.',upscRelevance:'India-China. SCO, AIIB, BRI.'},
{id:'wc6',name:'Cairo',lat:30.0444,lng:31.2357,type:'city',info:'Egypt. On Nile. Arab League HQ.',upscRelevance:'Nile civilization. Suez Canal. GERD.'},
{id:'wc7',name:'Addis Ababa',lat:9.025,lng:38.7469,type:'city',info:'Ethiopia. African Union HQ. ~2,400m.',upscRelevance:'AU HQ. BRICS expansion. GERD dispute.'},
{id:'wc8',name:'Kyiv',lat:50.4501,lng:30.5234,type:'city',info:'Ukraine. Dnieper River. Russia-Ukraine conflict.',upscRelevance:'Russia-Ukraine war. India neutrality. Energy security.'},
{id:'wc9',name:'Taipei',lat:25.033,lng:121.5654,type:'city',info:'Taiwan. TSMC — semiconductors. One China policy.',upscRelevance:'Taiwan Strait tensions. Semiconductor supply chain.'},
{id:'wc10',name:'Jakarta',lat:-6.2088,lng:106.8456,type:'city',info:'Indonesia. ASEAN secretariat. Capital moving to Nusantara.',upscRelevance:'ASEAN HQ. Capital relocation. Sinking city.'},
{id:'wc11',name:'Djibouti',lat:11.5806,lng:43.1425,type:'city',info:'Bab-el-Mandeb. China\'s first overseas military base.',upscRelevance:'China military base. Bab-el-Mandeb control.'},
{id:'wc12',name:'Brasília',lat:-15.7975,lng:-47.8919,type:'city',info:'Brazil. Planned city. BRICS member.',upscRelevance:'BRICS. Amazon policy. Planned capital.'},
{id:'wr1',name:'Nile',lat:25.0,lng:32.5,type:'river',info:'~6,650 km. Longest (disputed). 11 countries. White+Blue merge at Khartoum.',upscRelevance:'Longest debate. GERD dispute. Nile civilization.'},
{id:'wr2',name:'Amazon',lat:-3.4653,lng:-58.38,type:'river',info:'~6,400 km. Largest by discharge (20% freshwater). 9 countries.',upscRelevance:'Largest by volume. Deforestation. "Lungs of Earth".'},
{id:'wr3',name:'Mekong',lat:15.87,lng:105.68,type:'river',info:'4,350 km. 6 countries. China dams affect downstream.',upscRelevance:'Mekong-Ganga Cooperation. China dam diplomacy.'},
{id:'wr4',name:'Congo',lat:-4.3226,lng:15.307,type:'river',info:'4,700 km. Deepest (~220m). Crosses equator TWICE.',upscRelevance:'Deepest river. Crosses equator twice. PYQ: 2023.'},
{id:'wr5',name:'Danube',lat:48.21,lng:16.37,type:'river',info:'2,850 km. Through 10 countries — most international.',upscRelevance:'Most international basin. EU waterway.'},
{id:'wr6',name:'Yangtze',lat:31.2304,lng:121.4737,type:'river',info:'6,300 km. Longest in Asia. Three Gorges Dam.',upscRelevance:'Longest in Asia. Three Gorges.'},
{id:'wr7',name:'Rhine',lat:51.9,lng:6.95,type:'river',info:'1,230 km. Major European trade route.',upscRelevance:'European trade artery.'},
{id:'wm1',name:'Kilimanjaro',lat:-3.0674,lng:37.3556,type:'mountain',info:'5,895m. Highest in Africa. Tanzania. Glacier retreat.',upscRelevance:'Highest in Africa. Climate change indicator.'},
{id:'wm2',name:'Ural Mountains',lat:60,lng:60,type:'mountain',info:'~2,500 km. Europe-Asia boundary. Old fold.',upscRelevance:'Europe-Asia boundary. Old fold mountains.'},
{id:'wm3',name:'Andes',lat:-13.1631,lng:-72.545,type:'mountain',info:'~7,000 km. Longest continental range. Aconcagua (6,961m).',upscRelevance:'Longest range. Aconcagua — highest in Americas.'},
{id:'wm4',name:'Alps',lat:46.8,lng:8.2,type:'mountain',info:'~1,200 km. Mont Blanc (4,808m). 8 countries.',upscRelevance:'Young fold mountains. River origins.'},
{id:'wm5',name:'Caucasus',lat:42.5,lng:44.5,type:'mountain',info:'Mt Elbrus (5,642m) — highest in Europe.',upscRelevance:'Europe\'s highest peak. Geopolitical corridor.'},
{id:'wm6',name:'Atlas Mountains',lat:33.5,lng:-1.5,type:'mountain',info:'NW Africa. Sahara barrier.',upscRelevance:'Sahara edge. Mediterranean climate barrier.'},
{id:'ws1',name:'Strait of Hormuz',lat:26.5667,lng:56.25,type:'strait',info:'Iran-Oman. ~39 km. ~20-25% of global oil.',upscRelevance:'Oil chokepoint. India energy security. PYQ: 2024, 2022.'},
{id:'ws2',name:'Strait of Malacca',lat:2.5,lng:101,type:'strait',info:'Malaysia-Sumatra. ~900 km. ~25% of global trade.',upscRelevance:'India A&N advantage. China Malacca Dilemma. PYQ: 2023.'},
{id:'ws3',name:'Bab-el-Mandeb',lat:12.5833,lng:43.3333,type:'strait',info:'"Gate of Tears". Yemen-Djibouti. Red Sea → Gulf of Aden.',upscRelevance:'Suez route. Yemen/Houthi crisis. PYQ: 2021.'},
{id:'ws4',name:'Bosphorus',lat:41.1194,lng:29.0764,type:'strait',info:'Istanbul. Marmara → Black Sea. Montreux Convention.',upscRelevance:'Russia-Ukraine — Black Sea access. Montreux Convention.'},
{id:'ws5',name:'Strait of Gibraltar',lat:35.97,lng:-5.6,type:'strait',info:'Spain-Morocco. ~14 km. Mediterranean ↔ Atlantic.',upscRelevance:'Mediterranean-Atlantic link. Migration.'},
{id:'ws6',name:'Taiwan Strait',lat:24.5,lng:119.5,type:'strait',info:'~180 km. Separates Taiwan from China.',upscRelevance:'US-China tensions. UNCLOS.'},
{id:'ws7',name:'Palk Strait',lat:10.0,lng:79.7,type:'strait',info:'India (TN) - Sri Lanka. Ram Setu.',upscRelevance:'India-SL. Sethusamudram. PYQ: 2024.'},
{id:'ws8',name:'Mozambique Channel',lat:-17.0,lng:42.0,type:'strait',info:'Mozambique-Madagascar. Warm current.',upscRelevance:'Indian Ocean trade. Madagascar biodiversity.'},
{id:'wd1',name:'Sahara',lat:23,lng:11,type:'desert',info:'Largest HOT desert. ~9.2M km². 11 countries.',upscRelevance:'Largest HOT (not overall — Antarctic!). UNCCD. Sahel.'},
{id:'wd2',name:'Atacama',lat:-23.8634,lng:-69.1328,type:'desert',info:'Driest non-polar place. Chile. Lithium, copper.',upscRelevance:'Driest desert. Lithium — EV supply chain.'},
{id:'wd3',name:'Antarctic Desert',lat:-82,lng:0,type:'desert',info:'LARGEST DESERT (14M km²). Polar. Ice sheet 2.16 km avg.',upscRelevance:'LARGEST DESERT (trap!). India: Maitri, Bharati stations.'},
{id:'wd4',name:'Gobi',lat:42.5,lng:105,type:'desert',info:'Mongolia-China. Cold desert. Rain shadow of Himalayas.',upscRelevance:'Cold desert. Rain shadow. Desertification.'},
{id:'wd5',name:'Arabian Desert',lat:22,lng:48,type:'desert',info:'2.3M km². Rub al Khali — largest sand desert.',upscRelevance:'Oil reserves. Rub al Khali. India energy source.'},
{id:'wpyq1',name:'Suez Canal',lat:30.4358,lng:32.3442,type:'pyq',info:'Egypt. Mediterranean ↔ Red Sea. 193 km. No locks. ~12% global trade.',upscRelevance:'Trade chokepoint. Suez Crisis 1956. PYQ: 2023, 2017.'},
{id:'wpyq2',name:'South China Sea',lat:14.5,lng:114,type:'pyq',info:'Nine-Dash Line. UNCLOS. Spratly, Paracel. PCA 2016.',upscRelevance:'UNCLOS. PCA ruling. India Act East. PYQ: 2024, 2022.'},
{id:'wpyq3',name:'Golan Heights',lat:33.01,lng:35.75,type:'pyq',info:'Israel-Syria. Captured 1967. Water resources.',upscRelevance:'Israel-Syria. UN resolutions. PYQ: 2022, 2019.'},
{id:'wpyq4',name:'Crimea',lat:44.9521,lng:34.1024,type:'pyq',info:'Russia annexed from Ukraine 2014. Sevastopol naval base.',upscRelevance:'Russia-Ukraine. International law. PYQ: 2022.'},
{id:'wpyq5',name:'Arctic Region',lat:78,lng:15,type:'pyq',info:'Arctic Council. Northern Sea Route. India Observer.',upscRelevance:'India Arctic Policy 2022. Climate. PYQ: 2023, 2021.'},
{id:'wpyq6',name:'Great Barrier Reef',lat:-18.2871,lng:147.6992,type:'pyq',info:'Largest coral reef. Australia. Bleaching events.',upscRelevance:'Coral bleaching. El Niño. PYQ: 2020, 2016.'},
{id:'wpyq7',name:'Panama Canal',lat:9.08,lng:-79.68,type:'pyq',info:'82 km. Lock-based. Pacific ↔ Atlantic.',upscRelevance:'Lock canal (vs Suez — no locks). PYQ: 2019.'},
{id:'wpyq8',name:'Horn of Africa',lat:9.0,lng:47.0,type:'pyq',info:'Somalia, Ethiopia, Eritrea, Djibouti. Piracy.',upscRelevance:'Piracy (IN ops). Bab-el-Mandeb. PYQ: 2022.'},
{id:'wpyq9',name:'Caspian Sea',lat:41.5,lng:51.0,type:'pyq',info:'Largest enclosed water body. 5 countries.',upscRelevance:'Lake/sea debate (2018). 5 countries. PYQ: 2021, 2018.'},
{id:'wpyq10',name:'Dead Sea',lat:31.5,lng:35.5,type:'pyq',info:'Lowest point on Earth (~-430m). Hypersaline. Shrinking.',upscRelevance:'Lowest point. Hypersaline. PYQ: 2017.'},
];

export const quizData=[
{q:'Which are west-flowing rivers?\n1. Narmada  2. Tapti  3. Mahanadi  4. Periyar',opts:['1 and 2 only','1, 2 and 4 only','1, 2 and 3 only','All'],ans:1,exp:'Narmada, Tapti (rift valley), Periyar (Kerala) flow west. Mahanadi flows EAST.',region:'india'},
{q:'"Ring of Fire" is associated with:',opts:['Atlantic Ocean','Indian Ocean','Pacific Ocean','Arctic Ocean'],ans:2,exp:'Pacific Ring of Fire — 75% of active volcanoes, 90% earthquakes.',region:'world'},
{q:'Which strait separates India from Sri Lanka?',opts:['Hormuz','Palk Strait','Ten Degree Channel','Eight Degree Channel'],ans:1,exp:'Palk Strait. Ten Degree — Andaman from Nicobar. Eight Degree — Minicoy from Maldives.',region:'india'},
{q:'Caspian Sea is bordered by how many countries?',opts:['3','4','5','6'],ans:2,exp:'5: Russia, Kazakhstan, Turkmenistan, Iran, Azerbaijan.',region:'world'},
{q:'Narmada originates from:',opts:['Mahabaleshwar','Amarkantak','Gangotri','Trimbakeshwar'],ans:1,exp:'Narmada — Amarkantak (MP). Krishna — Mahabaleshwar. Ganga — Gangotri. Godavari — Trimbakeshwar.',region:'india'},
{q:'Deepest river in the world:',opts:['Amazon','Nile','Congo','Yangtze'],ans:2,exp:'Congo — depths >220m. Also crosses equator twice.',region:'world'},
{q:'Barren Island volcano is in:',opts:['Lakshadweep','Andaman Sea','Bay of Bengal','Arabian Sea'],ans:1,exp:'Only active volcano in India/South Asia. Andaman Sea (not Bay of Bengal!).',region:'india'},
{q:'Largest desert in the world:',opts:['Sahara','Gobi','Antarctic','Arabian'],ans:2,exp:'Antarctic (14M km²) is LARGEST. Sahara = largest HOT desert. Common trap!',region:'world'},
{q:'Match correctly:\n1. Wular — Largest freshwater\n2. Chilika — Largest brackish\n3. Sambhar — Largest inland saline',opts:['1 and 2 only','2 and 3 only','1 and 3 only','All correct'],ans:3,exp:'All correct. Wular (J&K), Chilika (Odisha), Sambhar (Rajasthan).',region:'india'},
{q:'GERD is on which river?',opts:['White Nile','Blue Nile','Congo','Niger'],ans:1,exp:'Blue Nile in Ethiopia. ~80% of Nile flow. Dispute with Egypt/Sudan.',region:'world'},
{q:'Palakkad Gap is a break in:',opts:['Eastern Ghats','Vindhya','Western Ghats','Aravalli'],ans:2,exp:'~40 km wide break in WG. NE monsoon into Kerala.',region:'india'},
{q:'Malacca Strait connects:',opts:['Red Sea & Med','Pacific & Atlantic','Indian & Pacific Ocean','Black Sea & Med'],ans:2,exp:'Indian Ocean → South China Sea (Pacific). ~25% global trade.',region:'world'},
{q:'Which is NOT west-flowing?\n1. Sabarmati  2. Mahi  3. Krishna  4. Luni',opts:['3 only','3 and 4','4 only','1 and 3'],ans:0,exp:'Krishna flows east. Sabarmati, Mahi, Luni all west. Luni — endorheic (Rann of Kutch).',region:'india'},
{q:'Montreux Convention regulates:',opts:['Suez Canal','Panama Canal','Turkish Straits','Hormuz'],ans:2,exp:'Montreux 1936 — Bosphorus & Dardanelles. Key in Russia-Ukraine context.',region:'world'},
{q:'Keibul Lamjao NP is unique because:',opts:['India\'s highest NP','Floating NP','Highest tiger density','Smallest NP'],ans:1,exp:'Only floating NP (Loktak Lake, Manipur). Sangai deer.',region:'india'},
{q:'Which canal has NO locks?',opts:['Panama','Suez','Kiel','All have locks'],ans:1,exp:'Suez — sea level, no locks. Panama uses locks.',region:'world'},
{q:'Atal Tunnel connects:',opts:['Srinagar-Leh','Manali-Lahaul Spiti','Shimla-Kinnaur','Jammu-Srinagar'],ans:1,exp:'Under Rohtang (Pir Panjal). World\'s longest above 10,000 ft.',region:'india'},
{q:'Nine-Dash Line is associated with:',opts:['India-Pak border','South China Sea','Israel-Palestine','Russia-Ukraine'],ans:1,exp:'China\'s SCS claim. Rejected by PCA 2016.',region:'world'},
];
